### ISSUE TITLE
Player - constructor should set eventMessage to a welcome message

### ISSUE THREAD

**Issue by zbialik** [zbialik/clue-less#102]
In the Player class, update the constructor for the Player object such that when a Player is initialized, their eventMessage is immediately set to: "Welcome to the game!"

**Comment by alex4287** [comment]
I'll play with this some more during the day - I got stuck/brain froze on this one. Tried different things in the player class and wasn't able to get it to show.

**Comment by zbialik** [comment]
@alex4287 

https://github.com/zbialik/clue-less/blob/main/src/main/java/clueless/Player.java#L28-L39

^ this is where the code update should be occurring. 

should be updating the eventMessage in BOTH constructors.
