### ISSUE TITLE
GameService - update eventMessage for when character moves to new location

### ISSUE THREAD

**Issue by zbialik** [zbialik/clue-less#104]
update needed in moveCharacterHTTP()

The current event message only shows something like "Alex moved professor plum to dining room". But this should also say something about awaiting their suggestion. 

Desired eventMessage:
"__ moved ___ to this room. Awaiting their suggestion"

**Comment by alex4287** [comment]
Please ignore the 2nd commit. Let me know if I need to fix anything. Thanks
