### ISSUE TITLE
Game - whoHasClue() - add logic

### ISSUE THREAD

**Issue by zbialik** [zbialik/clue-less#32]
Loop over the ordered list of characters (make sure to account for whose turn it is right now) and use the Player.hasClue() helper to determine if that player has a clue.

NOTE: you will want to first check if character is instanceof Player, then you will cast the Character to Player and then check if Player.hasClue()

- you can see example of this kinda casting logic in Game.getPlayer() and GameService.createPlayerInGameHTTP()

**Comment by mgtucks** [comment]
Added logic to who had clue method

**Comment by zbialik** [comment]
this should not have been closed as it was not merged to main branch
